openapi: 3.0.0
info:
  title: Event API
  version: 1.0.0
  description: API documentation for event endpoints

paths:
  /api/events:
    get:
      tags:
        - Event
      summary: Get all events
      description: Returns a list of all events
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    post:
      tags:
        - Event
      summary: Create event
      description: Creates a new event
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEvent'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /api/events/stats:
    get:
      tags:
        - Event
      summary: Get event statistics
      description: Returns statistics about events
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /api/events/{id}:
    get:
      tags:
        - Event
      summary: Get event by ID
      description: Returns an event by its ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    put:
      tags:
        - Event
      summary: Update event
      description: Updates an event by its ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEvent'
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    delete:
      tags:
        - Event
      summary: Delete event
      description: Deletes an event by its ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'